### ISSUE TITLE
Profil plant

### ISSUE THREAD

**Issue by benaja-bendo** [benaja-bendo/frontend-arosaje#3]
- [x] les informations sur la plant
- [x] vue sur l'entretien de la plant

**Comment by mourtadabel** [comment]
@benaja-bendo peux tu m'expliquer stp qu'est ce que tu veux dire plus par vue sur l'entretien de la plante
J'ai crée une vue ou il y aura à gauche l'image de la plante  et à droite  toute la description de la plante  avec un boutton "contacter" , si tu peux jeter un coup d'oeil sur mon dernier push

**Comment by benaja-bendo** [comment]
> @benaja-bendo peux tu m'expliquer stp qu'est ce que tu veux dire plus par vue sur l'entretien de la plante J'ai crée une vue ou il y aura à gauche l'image de la plante et à droite toute la description de la plante avec un boutton "contacter" , si tu peux jeter un coup d'oeil sur mon dernier push

c'est une page qui permet d'avoir des informations sur la plante qui va être garder, avec qui a publier, les conseils pour le garder, etc. plus de détail sur le document.
